Use calcfunction for getitem in `For` loop workgraph
aiidateam/aiida-workgraph pull request #283
Opened 2024-08-28 08:48 UTC by agoscinski

To track the provenance in the for loop we now use a calcfunction to track provenance for the `For` loop workgraph. I would like to allow more types than integers for the sequence, but I am not sure how to generically test for types that are supported by aiida core. Some orm types have a `_type` class attribute, but not all of them.

2024-08-28 09:41 UTC, superstar54 commented
Hi @agoscinski , thanks for the work.

There is a function `orm.to_aiida_type` which can serialize the data automatically, and you can check which Python data types it support.


It's also would be good if the user can supply a list of AiiDA data as the input for `sequence`, e.g.,
```python
[structure0, structure1, ...]
```

Because AiiDA does not support a list of AiiDA data as input, internally, we can change it to a dict with keys, the keys keep the order information.
```python
{"sequence_0": structure0, ...}
```

and then, in the WorkGraph engine, if the sequence is a dict, we get the AiiDA data directly without serialization.

2024-09-02 10:07 UTC, agoscinski commented
Thanks @superstar54 applied your suggestion. The test pass, but it does not test the other use cases you mentioned. I tried to implement a dictionary, but it is a bit opaque to me how to change the iterator to be compatible with dictionaries that use hashable keys. It seems the iterator is hard coded to only work for collections that can be accessed by incremental increasing numbers like lists.  Maybe we should generalize this for arbitrary generators. Not sure if this PR is the right place.

2024-09-03 08:23 UTC, superstar54 requested changes
Hi @agoscinski , thanks for the work! 

Please test for the changes.

As mentioned in my previous comment, if you use a list of orm.data as the sequence, it will raise an error, because we need to change the list to a dict.

Therefore, you need also modify the `aiida_workgraph.workgraph.WorkGraph` to convert it into a dict. Then inside the engine, the sequence is a dict.

2024-09-03 08:23 UTC, superstar54 commented on aiida_workgraph/engine/workgraph.py
> +                # only convert value f not already orm type because sequence
```suggestion
                # only convert value if not already orm type because sequence
```

2024-09-17 09:48 UTC, agoscinski commented
> As mentioned in my previous comment, if you use a list of orm.data as the sequence, it will raise an error, because we need to change the list to a dict.

That is for non json serializable data types like `orm.StructureData` for others it will automatically convert it and is not a problem. My problem with the dynamic workaround is that in this case it is shown differently in the provenance graph and also will create a lot of links.

That was the initial idea
```python
@calcfunction
def __getitem__(seq, idx):
    return orm.to_aiida_type(seq[idx.value])

node = __getitem__([1,2,3], 0)
generate_node_graph(node.pk)
```
<img width="438" alt="Screenshot 2024-09-17 at 11 34 09" src="https://github.com/user-attachments/assets/fccabbb1-774a-4551-b557-048bf0abe24f">

but the dynamic input ports approach gives
```python
import numpy as np

@calcfunctione
def __getitem__(**kwargs):
    idx = kwargs.pop('idx')
    list_of_orms = list(kwargs.values())
    return list_of_orms[idx.value].clone()

inp = {f'list_of_orms_{i}': orm.StructureData(cell=np.random.rand(3,3)) for i in range(3)}
inp['idx'] = orm.Int(0)
node = __getitem__(**inp)
generate_node_graph(node.pk)
```
<img width="1319" alt="Screenshot 2024-09-17 at 11 35 36" src="https://github.com/user-attachments/assets/15f01dfa-6caa-4e04-a6c1-0e4e8b157652">

There is also the new StructureData object that might be json serializable because of the `BaseModel` that resolves this issue. I am also concerned by performance, since we now have to convert a Generator to a list which can be quite time consuming. I feel more and more that we should drop this PR. With the `For` workgraph we can maybe go more into a similar direction as with the while loop and just focus and a nice GUI representation.

2025-07-20 13:57 UTC, superstar54 commented
The `For` and `While` WorkGraph types are dropped and not used anymore. Instead, the `Map` and `While` context managers are used. Hence, I am closing this PR.

2025-07-20 13:57 UTC, closed without merging