Allow mixed `str`/`dict` inputs/outputs to tasks
aiidateam/aiida-workgraph pull request #345
Opened 2024-11-19 08:52 UTC by GeigerJ2

2024-11-19 16:20 UTC, superstar54 requested changes
@GeigerJ2 , thanks for the work!

Could you also update the docs to tell the user that we have these options.
e.g., https://aiida-workgraph.readthedocs.io/en/latest/concept/autogen/task.html
another one

2024-11-19 16:20 UTC, superstar54 commented on aiida_workgraph/utils/__init__.py
> +    :param list_type: "input" or "output" to indicate what is to be validated for better error message.
```suggestion
    :param list_type: "inputs" or "outputs" to indicate what is to be validated for better error message.
```

2024-11-19 17:47 UTC, GeigerJ2 commented
> @GeigerJ2 , thanks for the work!
> 
> Could you also update the docs to tell the user that we have these options. e.g., [aiida-workgraph.readthedocs.io/en/latest/concept/autogen/task.html](https://aiida-workgraph.readthedocs.io/en/latest/concept/autogen/task.html)

Cheers! Yes, good catch, I will add it!

2024-12-02 12:44 UTC, superstar54 approved these changes
LGTM!

2024-12-02 13:00 UTC, merged