Hide metadata inputs for tasks in HTML visualization.
aiidateam/aiida-workgraph pull request #346
Opened 2024-11-19 10:55 UTC by GeigerJ2

2024-11-19 15:41 UTC, superstar54 commented on aiida_workgraph/widget/src/widget/__init__.py
> +                if not input_k.startswith("metadata"):
I think we still show the top-level `metadata` port, but not expand it.
```suggestion
                if not input_k.startswith("metadata."):
```

2024-11-20 07:50 UTC, superstar54 requested changes
Hi @GeigerJ2 , instead of handling `metadata` specially, it would be good to also handle other namespace ports. I suggest to use a parameter to control it.
For example, we can add an attribute to the node, e.g., `show_socket_level`, and the default value is `0` to only the top level, if it is `1`, then show all `root.sub`, and so on.

2024-11-20 09:48 UTC, GeigerJ2 commented
> Hi @GeigerJ2 , instead of handling `metadata` specially, it would be good to also handle other namespace ports. I suggest to use a parameter to control it. For example, we can add an attribute to the node, e.g., `show_socket_level`, and the default value is `0` to only the top level, if it is `1`, then show all `root.sub`, and so on.

Nice idea, I like it! Will implement it!

2024-11-20 15:55 UTC, GeigerJ2 commented
Hi, @superstar54, I generalized it in my latest commit. The namespace nesting depth for the shown sockets can now be controlled by a parameter of the `to_html` method of a `Task`. I assumed this nesting only applies to top-level keys, and I'm not sure if this covers all use cases. So please let me know if something else comes to mind here. I'll add tests then afterwards.

2024-11-26 10:13 UTC, superstar54 commented
Thanks for the update!
apart from the HTML, it also good to add `show_socket_depth` as a attribute of `Task`, and then use it in the widget, as follow:

```diff
def _repr_mimebundle_(self, *args: Any, **kwargs: Any) -> any:

        if self._widget is None:
            print(WIDGET_INSTALLATION_MESSAGE)
            return
        # if ipywdigets > 8.0.0, use _repr_mimebundle_ instead of _ipython_display_
+        self._widget.from_node(self, show_socket_depth=self.show_socket_depth)
-        self._widget.from_node(self)
        if hasattr(self._widget, "_repr_mimebundle_"):
            return self._widget._repr_mimebundle_(*args, **kwargs)
        else:
            return self._widget._ipython_display_(*args, **kwargs)
```
This way, the user can control the widget.

2024-12-02 13:08 UTC, superstar54 approved these changes
LGTM!

2024-12-02 13:25 UTC, merged